### ISSUE TITLE
is it possible to get tldr summary part 

### ISSUE THREAD

**Issue by NATEHUAIZE** [danielnsilva/semanticscholar#102]
Thanks for your time！ 
I wonder whether it is possible to get tldr part

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by danielnsilva** [comment]
Yes, you just need to access the `tldr` property of the paper object, like this:

```python
from semanticscholar import SemanticScholar
sch = SemanticScholar()
paper = sch.get_paper('10.1093/mind/lix.236.433')
print(paper.tldr)
```
