### ISSUE TITLE
Searching with keywords

### ISSUE THREAD

**Issue by dwaipayanroy** [danielnsilva/semanticscholar#35]
Can we have a search mechanism for searching papers based on some keyword queries? There is already an API call for that:
https://api.semanticscholar.org/graph/v1/paper/search?query=word+embedding+automatic+query+expansion&fields=title,abstract

**Comment by danielnsilva** [comment]
I've been working ([dev branch](https://github.com/danielnsilva/semanticscholar/tree/dev)) to deliver a new release based on the recent Semantic Scholar API upgrade, which includes searching for papers by keyword.

**Comment by wookayin** [comment]
Hi, I'm looking forward to this feature. Any chance you've gotten recently to wrap this feature up?

**Comment by danielnsilva** [comment]
Hi, @wookayin.

Unfortunately, I've been overloaded the last few months with other projects and haven't found enough time to work on this one.

But I have some code already done and will give my best to release a new version that enables the search feature soon. Maybe until next week.

**Comment by danielnsilva** [comment]
I think your viewpoint is correct on that @zouharvi . I am currently working on how to deal with paginated results. I intend to allow the user to iterate over results regardless number of pages.

**Comment by danielnsilva** [comment]
After a long delay, the new version was released and the search feature is finally here. Hope it is helpful.
