### ISSUE TITLE
HTTP status 403 Forbidden error

### ISSUE THREAD

**Issue by quicly** [danielnsilva/semanticscholar#38]
When I'm trying to access paper data i get error:

`raise PermissionError('HTTP status 403 Forbidden.')`

I was able to get some data yesterday. But today it does not working again

example code
```
from semanticscholar import SemanticScholar
sch = SemanticScholar(timeout=2)
paper = sch.paper("10.2307/2393374")
test = paper['references']
print(test)
```

**Comment by quicly** [comment]
Oh, probably it is somehow explained by the fact when i'm visiting https://api.semanticscholar.org/ i get message
```
{"message":"Forbidden"}
```

**Comment by zouharvi** [comment]
Hi, this seems to be an error on SemanticScholar's side. https://twitter.com/zouharvi/status/1570704121384292352

**Comment by danielnsilva** [comment]
It seems the API service came back online again.
