### ISSUE TITLE
PDF of a paper

### ISSUE THREAD

**Issue by zouharvi** [danielnsilva/semanticscholar#40]
Papers on SemanticScholar often include a link to a PDF to a paper ([example](https://www.semanticscholar.org/paper/A-Study-on-Word-Similarity-using-Context-Vector-Chen-You/0b09178ac8d17a92f16140365363d8df88c757d0)). Is there a way to access this link via the SemanticScholar API or not? If not, then what's the easiest way to obtain the said PDF?

I suppose that if `ACL` is in `externalIds` then one can construct the pfd link as `f"https://aclanthology.org/{ACL}.pdf"` which however is not very elegant.

This is maybe a general question regarding the API and not of this project but I'd still hope that someone would know the answer.

**Comment by danielnsilva** [comment]
I think your suggestion to construct links based on ```externalds``` may be valid for some cases.

There is no mention of PDF links in [the official documentation](https://api.semanticscholar.org/api-docs/graph). However, I just found out recently that the search page makes calls to an undocumented endpoint which returns some fields that may contain links to PDFs if available.

Try out:

```python
import requests
import json

reqUrl = "https://www.semanticscholar.org/api/1/search"

headersList = {
 "Accept": "*/*",
 "Content-Type": "application/json" 
}

payload = json.dumps({
  "queryString":"A Study on Word Similarity using Context Vector Models",
  "pageSize":1,
  "page":1,
  "sort":"relevance",
  "authors":[],
  "coAuthors":[],
  "venues":[]
})

r = requests.request("POST", reqUrl, data=payload,  headers=headersList)

print(r.json()["results"][0]["links"])
print(r.json()["results"][0]["primaryPaperLink"])
print(r.json()["results"][0]["alternatePaperLinks"])
```
Output:

```console
[{'url': 'https://www.aclweb.org/anthology/O02-2002.pdf', 'linkType': 'acl'}]
{'url': 'https://www.aclweb.org/anthology/O02-2002.pdf', 'linkType': 'acl'}
[{'url': 'http://aclweb.org/anthology/O02-2002', 'linkType': 'anansi'}, {'url': 'http://www.aclclp.org.tw/clclp/v7n2/v7n2a2.pdf', 'linkType': 'dblp'}, {'url': 'http://www.aclweb.org/anthology/O/O02/O02-2002.pdf', 'linkType': 'crawler'}, {'url': 'https://doi.org/10.30019/IJCLCLP.200208.0002', 'linkType': 'doi'}]
```

**Comment by zouharvi** [comment]
This is wonderful, thanks!
