### ISSUE TITLE
Tim Berners-Lee author search gives 0 results

### ISSUE THREAD

**Issue by WolfgangFahl** [danielnsilva/semanticscholar#44]
```python 
def testSearchAuthor(self):
        """
      test autor search
        """
        results=sch.search_author("Tim Berners-Lee")
        print(results.total)
```
compare to https://www.semanticscholar.org/search?q=Tim%20Berners-Lee&sort=relevance

and https://www.semanticscholar.org/author/Tim-Berners-Lee/1403176300

**Comment by danielnsilva** [comment]
Hi @WolfgangFahl 

It looks like an S2AG API-related issue, maybe a limitation.
> https://api.semanticscholar.org/graph/v1/author/search?query=Tim%20Berners-Lee

Not sure if both S2AG API and the portal search should return the same results. Possibly the portal performs a more comprehensive search than API (which searches authors by name). However, I agree that the search should not give 0 results. 

Removing the "-Lee" term from the query will return some results.

> https://api.semanticscholar.org/graph/v1/author/search?query=Tim%20Berners

Output:
```
{
    total: 8,
    offset: 0,
    data: [
        {
            authorId: "2110767564",
            name: "Tim Lee"
        },
        {
            authorId: "1409459693",
            name: "C. T. Berners-Lee"
        },
        {
            authorId: "1410784374",
            name: "D. T. Berners-Lee"
        },
        {
            authorId: "1432678629",
            name: "T. Berners-Lee"
        },
        {
            authorId: "1409503491",
            name: "Sir Tim Berners-Lee"
        },
        {
            authorId: "2068756150",
            name: "Tim Berners-Lee"
        },
        {
            authorId: "1403176300",
            name: "Tim Berners-Lee"
        },
        {
            authorId: "2141911475",
            name: "Tim Berners Lee"
        }
    ]
}
```

**Comment by danielnsilva** [comment]
I will close this issue. Please re-open it if you have any questions on this issue.
