### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by firmianay** [danielnsilva/semanticscholar#51]
https://www.semanticscholar.org/paper/Detection-of-Repackaged-Android-Malware-with-Tian-Yao/c4685a31bcd83dd2c3c7ec8e741058c43203c61e
```
>>> from semanticscholar import SemanticScholar
>>> sch = SemanticScholar()
>>> title = 'Detection of Repackaged Android Malware with Code-Heterogeneity Features.'
>>> search_query = sch.search_paper(title)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/semanticscholar/SemanticScholar.py", line 353, in search_paper
    results = PaginatedResults(
  File "/opt/homebrew/lib/python3.10/site-packages/semanticscholar/PaginatedResults.py", line 38, in __init__
    self.__get_next_page()
  File "/opt/homebrew/lib/python3.10/site-packages/semanticscholar/PaginatedResults.py", line 101, in __get_next_page
    self._data = results['data']
KeyError: 'data'
```

**Comment by danielnsilva** [comment]
It appears that the issue is related to #44, which means that it is possibly an S2 API-related issue. The problem seems to be caused by the hyphen in the search term.

```python
from semanticscholar import SemanticScholar
sch = SemanticScholar()
title = 'Detection of Repackaged Android Malware with Code Heterogeneity Features.'
search_query = sch.search_paper(title)
print(f'Total results: {search_query.total}')
```

Output:
```python
Total results: 2
```

Also, try these different variations of the search term by directly calling the API.

Replacing hyphen with space:
> https://api.semanticscholar.org/graph/v1/paper/search?query=Detection%20of%20Repackaged%20Android%20Malware%20with%20Code%20Heterogeneity%20Features.

With space after the hyphen:
> https://api.semanticscholar.org/graph/v1/paper/search?query=Detection%20of%20Repackaged%20Android%20Malware%20with%20Code-%20Heterogeneity%20Features.

**Comment by firmianay** [comment]
This problem is very strange, after I removed the hyphen, the situation improved a lot, thanks a lot for this tip.
