### ISSUE TITLE
Adding some additional filter arguments to get_recommended_papers_from_lists

### ISSUE THREAD

**Issue by bgriffen** [danielnsilva/semanticscholar#55]
Would it be possible to add one or two additional filter arguments to the great function [get_recommended_papers_from_lists](https://github.com/danielnsilva/semanticscholar/blob/84225660550a6477c0d92ed84d4f124047fa223b/semanticscholar/SemanticScholar.py#L560)? I may have missed it, but being able to add e.g. a publication date range would be fantastic. It seems like the papers returned are the most recent but being able to filter on this would then allow the package to be used as a more general weekly or monthly recommendation system. I saw "pool" by "recent" etc. in other functions, so even something similar to that would be ideal. Only option I can think of is to just query frequently then hope that the returned results have the new recommendations from since last search and just keep a record of ones that have been used before.

```python
    def get_recommended_papers_from_lists(
                self,
                positive_paper_ids: List[str],
                negative_paper_ids: List[str] = None,
                fields: list = None,
                limit: int = 100,
                publicationDate_min: datetime, ## for example
                publicationDate_max: datetime ## adding something similar
            ) -> List[Paper]:
```
Thanks for great package, I'd be using it every week should this option become available.

**Comment by bgriffen** [comment]
Certainly understand. Also appreciate that what you have here is a reflection of the availability of the API. I'm already on the Slack community :). Is there perhaps any information about the returned results of [get_recommended_papers_from_lists](https://github.com/danielnsilva/semanticscholar/blob/84225660550a6477c0d92ed84d4f124047fa223b/semanticscholar/SemanticScholar.py#L560) that you might know? Are the results returned in order of relevance? I noticed the dates are always fairly recent so is there perhaps some pre-filtering taking place? For now, I guess I just will query it once a week and take the top N papers from the dataframe sorted by `publishedDate`. Hopefully some more nice features keep coming from the API side soon!

**Comment by danielnsilva** [comment]
I believe the results are indeed ordered by relevance. If you set a limit to 10, you should get the top 10 recommended papers. Increase it to 11, and you'll notice those first 10 stay consistent in their order.
As for the endpoint that returns recommendations based on positive and negative example lists, AFAIK, the results are limited to papers published within the last 60 days.

**Comment by danielnsilva** [comment]
I'm closing this issue for now, but feel free to reach out if you have any more questions.
