### ISSUE TITLE
I can't use offset and limit parameters in the getpaper method

### ISSUE THREAD

**Issue by hugoduca** [danielnsilva/semanticscholar#59]
I'm using the method https://api.semanticscholar.org/api-docs/graph#tag/Paper-Data/operation/get_graph_get_paper_citations

Here's my code snippet:
```
  references = sch.get_paper(str(paper['paperId']) + "/references", fields=['contexts','paperId' ,'externalIds','intents','isInfluential','abstract','publicationDate ','title','venue','authors','year'])
```
It is working very well, however, the api limits the results to 1000 citations, in my dataset, I have articles with more than 4 thousand references, for this reason, I tried to use offset and limit, as suggested in the referenced documentation, however, I cannot include offset within fields, as it returns an error, it was also not possible to include either the offset parameter or the limit parameter directly in the URL.

It would be very useful for the library to be able to use these parameters.

**Comment by danielnsilva** [comment]
To fetch paper citations, follow this approach:

```python
from semanticscholar import SemanticScholar
sch = SemanticScholar()
references = sch.get_paper_citations('10.1093/mind/lix.236.433')
all_references = list(references)
print(len(all_references))
```

Output:
```console
9656
```

Check it out on Replit: https://replit.com/@danielnsilva/semanticscholar-issue-59

**Comment by hugoduca** [comment]
It worked, thank you very much.
