### ISSUE TITLE
Is there a way to get the list of cited papers of a paper (given this paper’s id)?

### ISSUE THREAD

**Issue by realliyifei** [danielnsilva/semanticscholar#77]

**Comment by danielnsilva** [comment]
```python
from semanticscholar import SemanticScholar

sch = SemanticScholar()
references = sch.get_paper_references('10.1007/BF01645742')
for r in references:
    print(r.paper.title)
```

Check it out on Replit: https://replit.com/@danielnsilva/semanticscholar-issue-77#main.py

**Comment by realliyifei** [comment]
Thank you it works! What is the source of these references? I notice that a few of them are not consistent with the ground truth references in the pdf (i.e. missing references, having extra references, or the references are not the same ones). Also, the ordering is not the same as ground truth so cannot map to the in-context citation index.
