### ISSUE TITLE
Extract Bibtex

### ISSUE THREAD

**Issue by shayne-longpre** [danielnsilva/semanticscholar#79]
Using get_paper() we can access its metadata, but none of it appears to have a preformatted version of its bibtex citation? Is this something that is available or can be reliably constructed with automatic methods?

**Comment by danielnsilva** [comment]
The `citationStyles` property with BibTeX is in the API but not in this package yet, and might be added in the next release.

**Comment by shayne-longpre** [comment]
@danielnsilva Thanks! Could you point me to how to get this from the API? Using `get_paper()`? I don't see it -- or at least it only appears for papers that the selected paper cited.

**Comment by danielnsilva** [comment]
I've just added support for the citationStyles property, but it has not yet been tested and is not included in any release. If you want to try it out, you can install it directly from the source.

```console
pip install --no-cache-dir --force-reinstall git+https://github.com/danielnsilva/semanticscholar@master
```
