### ISSUE TITLE
Difference between FieldsOfStudy and s2FieldsOfStudy?

### ISSUE THREAD

**Issue by realliyifei** [danielnsilva/semanticscholar#81]
What is the difference between FieldsOfStudy and s2FieldsOfStudy? I also notice every paper contain a valid s2FieldsOfStudy, but a few of them has None FieldsOfStudy. If I need to analyze the field distribution of the papers, is it better to use s2FieldsOfStudy since it is more complete?

**Comment by danielnsilva** [comment]
> `s2FieldsOfStudy` is a replacement for `fieldsOfStudy`, the latter will be deprecated and removed eventually.

Source: https://github.com/allenai/s2-folks/blob/main/FAQ.md#what-is-the-difference-between-fieldsofstudy-and-s2fieldsofstudy
