### ISSUE TITLE
Citations list maxes out at 1000

### ISSUE THREAD

**Issue by alecjacobson** [danielnsilva/semanticscholar#82]
I'm trying to use semanticscholar to do some cross referencing of papers and their citations. For this, I'm iterating and examining every citation. I thought that `paper.citation` would list _all_ citations, but it seems to just list 1000 of them:

```python
from semanticscholar import SemanticScholar
sch = SemanticScholar(timeout=10)
paper = sch.get_paper('a6cb366736791bcccc5c8639de5a8f9636bf87e8')
print(f"len(paper.citations) = {len(paper.citations)} but paper.citationCount = {paper.citationCount}")
```

Is there a way to get _all_ citations?

**Comment by alecjacobson** [comment]
Oh, in this example I'm seeing output:

```
len(paper.citations) = 1000 but paper.citationCount = 130637
```

**Comment by danielnsilva** [comment]
The limitation you’re encountering is inherent to the S2AG API. If you need access to more than 1,000 citations, you can try `get_paper_citations()` method (refer to [this answer](https://github.com/danielnsilva/semanticscholar/issues/59#issuecomment-1826411533) on a related issue #59). However, be aware that this method also has a limit, restricting the results to 9,999 citations. If you  still need to exceed this limitation, you can download [the full-corpus datasets](https://api.semanticscholar.org/api-docs/datasets).

**Comment by alecjacobson** [comment]
Understood! Thanks Daniel.
