### ISSUE TITLE
How to get list of outputs without concerning several invalid inputs

### ISSUE THREAD

**Issue by realliyifei** [danielnsilva/semanticscholar#85]
When we process a bunch of document, we first get the `list_of_corpusid` and input them once by `sch.get_papers(list_of_corpusid)` to get a list of outputs so that we can save time. 

However, when one or several of the inputs are invalid corpusid, the whole outputs would fail. This is painful when processing large corpus because we cannot guarantee that all corpusid are valid and the batch-processing is always interrupted.

**Comment by danielnsilva** [comment]
Hi @realliyifei 

This is related to #80. Please take a look at [this comment](https://github.com/danielnsilva/semanticscholar/issues/80#issuecomment-1880068806). This fix will be part of the next release.
