### ISSUE TITLE
Can we wrap the 500 or 504 Exception to a more specific Exception

### ISSUE THREAD

**Issue by j-z10** [danielnsilva/semanticscholar#88]
### Proposed change description

Sometimes, when we try to get data from semantic scholar server,  the http response status code may be 500 or 504, and it's json message is "Endpoint request timeout". 

Then the `semanticscholar.ApiRequester` will [raise an Exception](https://github.com/danielnsilva/semanticscholar/blob/master/semanticscholar/ApiRequester.py#L140) as below.
 <img width="664" alt="image" src="https://github.com/danielnsilva/semanticscholar/assets/13131481/c0237237-0c4b-4ae3-9203-862b4bfd4e91">

For some reason, we may want to ignore this error and retry calling that endpoint again, Therefore, if this Exception is more specific, it would be much more helpful to us.

What about create a new `semanticscholar.ServerInternalException`,  and `raise ServerInternalException(data['message'])` instead when we got 500 or 504 response. So, we can catch this `ServerInternalException` like this.
```python
client = AsyncSemanticScholar()
try:
    papers = await client.get_papers(['some-id'])
except ServerInternalException:
    papers = client.get_papers(['some-id']) # call it again
```

Thanks.

**Comment by danielnsilva** [comment]
I like your suggestion and would like to enhance it a bit. We could avoid raising generic exceptions, as you suggested, and create specific exceptions for each status code: `InternalServerErrorException` for status 500 and `GatewayTimeoutException` for status 504. Additionally, we can have a base exception class, `ServerErrorException`, that both specific exceptions will inherit from. This way, you can catch the particular exceptions or handle both cases using the base exception.

```python
class ServerErrorException(SemanticScholarException):
    '''A base class for HTTP Status Code 5xx errors.'''

class InternalServerErrorException(ServerErrorException):
    '''HTTP Status Code 500.'''

class GatewayTimeoutException(ServerErrorException):
    '''HTTP Status Code 504.'''
```
