### ISSUE TITLE
Would you please upgrade pip version?

### ISSUE THREAD

**Issue by wyh** [danielnsilva/semanticscholar#9]
Daniel,

Would you please upgrade pip version? 

You might add a .travis config just like the following one: `https://github.com/wyh/semanticscholar/blob/master/.travis.yml`

After adding travis, it will build and deploy pip automatically.

**Comment by danielnsilva** [comment]
PyPI package published. I set up GitHub Actions to build and deploy the PyPI package. I should have done it much earlier. Thanks!
