### ISSUE TITLE
`nest_asyncio` not compatible with modern python environments

### ISSUE THREAD

**Issue by dmoklaf** [danielnsilva/semanticscholar#92]
This library uses `nest_asyncio` to provide a synchronous API based on its asynchronous API, e.g. :

https://github.com/danielnsilva/semanticscholar/blob/1d94dfff5fa433037f009bd6471e4bd5f86dbc91/semanticscholar/PaginatedResults.py#L43

However, even when using this library in asynchronous mode only, `nest_asyncio` is still imported.

Unfortunately, the `nest_asyncio` library is not maintained anymore (sadly its author erdewit has passed this year) and is incompatible with some modern python environments like `uvloop`:
https://github.com/erdewit/nest_asyncio/issues/49

`nest_asyncio` shall be imported only when the synchronous API is called.

**Comment by danielnsilva** [comment]
Do you mean to import `nest_asyncio` only before calling `run_until_complete()` in `_get_next_page()`? If so, could you please test this approach and open a pull request?

I am aware of what happened with the author and the lack of maintenance of `nest_asyncio`, but I haven't found an alternative solution yet.

**Comment by dmoklaf** [comment]
Exactly
This would reduce the bug’s impact surface greatly (basically removing it for all async users, but keeping it for some sync users).

I can publish a pull in a couple days.
